a, b = input().split()
c, d = input().split()
e, f = input().split()
g, h = input().split()
i, j = input().split()

a = int(a)
b = int(b)
c = int(c) 
d = int(d)
e = int(e)
f = int(f)
g = int(g)
h = int(h)
i = int(i)
j = int(j)

def trocarAB(a, b, c, d, e, f, g, h, i, j):
    print(b,a)
    print(d,c)
    print(f,e)
    print(h,g)
    print(j,i)
       
trocarAB(a, b)
trocarAB(c, d)
trocarAB(e, f)
trocarAB(g, h)
trocarAB(i, j)